# Generated by Django 4.0.10 on 2023-05-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_discount_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_rate',
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.IntegerField(blank=True, null=True)),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
