# Generated by Django 4.0.10 on 2023-05-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_discount_product_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
